travis:
  secure:
    BINSTAR_TOKEN: gdNosF97qU39nFEmpKpmX4QWbRZHle+x/Hiist9CK3pHzsFvh8WbejysvtT1Dc4RyeiDdY4J8r5nE3FGq2s3xLCDMCZoCYBuDLMHoypVUofNr43JwgryTOp/pIJOIBHpVdPxE/4n5mxXR7L5duphfWDAsj3UmuKgCgoMfsyk8SRjpKcvGsITA12A4Sp26Em5objWzW2rXnkmPdB5/1F3qHv8sjbrcxQt3vOCQ3gISAnqpoLqnKub3lWlInA1PKZ7UAONiGauC4RAZfqV3zAEQMd0OE1MlpOFnrdjx6aYG5JBMQiFU1d7T0Yr9xPaN73YdvvIfgTScdM5LyqoJ8Wk23Kom5/Rz6h7X3dj5egSxXBYQsd5tQh8wCsMAwlAmFScFvvfjhPQqmx/x6JeHCgBBfPc0BP5R8FjvrRXVSiOSK9V1gzbH2KWonInfVkP3R/Mp5vPJnrMkQ8CvO0fM0NzNR0l10Z9LtLbf9Nra1f9YxNBrYb9zS6Gv/5pKgwf2uU3/DtHqhmEVX63AaW8r+qw6xmtRO5UrG1uJysGIxoiI7eZSFRlZaYeQ1wdwOzby6qOYsRWVAFH7Qbhw8DGw29VBG639XR+k3Nc+2hZ2WBq438Y/oKm9a6ltB0YtoMEOhT8E6bmKnyRHAnJffgmh35Q/YmJ7SxcDGmpheAdL9cQxjE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
