travis:
  secure:
    BINSTAR_TOKEN: LqACXEvvFAtslivHiNU1Fs8vMVVjxPtjfuqzTgTOUwquQUMsOdODuzdvESMWAAQRm7rim10sgy2FXCdDVzLz/6jA9LDFTMpKvzPkEdWUJUdpca2pIk+OHfdRHM7rB8grwwelFxUj7rLygVHB/M1yDa53fQXyiQqg+k6LiHu2JFPHg4Cd/BRpaYeyS3ACz9Q9Dok4uwvX1s0YFsTpafjHqpyBEszoMtFJcMZO/IT3brunmNFMSgsHVZIyh2vkxSu288zmmYna50ErUZQjooBQWqhzA40p31PjgQvbclU3gpKu+krLIiHUTZ2a0qw/Wtm3W153MY7gBNesGmiPdJnNNRXkqwXyZQ7Ym/Pje1VT5APJ6Rpn2ozxHDsKbndSZkHHJ1N0D+jiG6e34WjpvMi3uor9E83Tc3XMU3NgRYX6E3GJwCRXwQlfdrdUdfkm3cEi2f9bkODgJj74iy5dYfHELIAnflOu0/mj2maFkzVjwhTk7LD8S/qIAhFyRcIeHcDzAbm6xM5evGFwX3MEiIgTjCWE34RTvTNk13ranpSxRgYKjBrUGRJU5GnR8Zci21n8eZPEtDXRX1XURZgksgWWmgOwBFPIiP8r/LYimNKBoh57uMIxPvRbdIdI6k7C2OMvP9cpzJm20C6vKpmOCqbvlaJmxsTfHoKy0WYhrGpVf0A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
